# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-27 07:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_banner_emailverifyrecord'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='gender',
            new_name='sex',
        ),
    ]
